version: "3.9"

services:
  web:
    build: ./web
    ports:
      - "80:5000"
    environment:
      - BACKEND_URL=http://backend:5001
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    expose:
      - "5001"
    restart: unless-stopped
